name: Trigger auto deployment for order-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/order-container-AutoDeployTrigger-5ce6d15f-ef95-4f91-ba6b-c2987ea69ee0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ORDERCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ORDERCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ORDERCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: order.azurecr.io
          registryUsername: ${{ secrets.ORDERCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORDERCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: order-container
          resourceGroup: OrderResource
          imageToBuild: order.azurecr.io/order-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


